import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// AIHomeworkMathSolver — generated by AppFactoryKit appgen from niche "ai-tutor-solver".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum AIHomeworkMathSolverFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "AIHomeworkMathSolver",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "text.bubble",
                          title: "AIHomeworkMathSolver",
                          message: "Photo a problem, get step-by-step solution."),
                    .init(systemImage: "sparkles",
                          title: "Go Pro",
                          message: "Unlimited solves, step-by-step, all subjects.")
                ],
                presentsPaywallOnFinish: true,
                accent: .blue
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock AIHomeworkMathSolver Pro",
                subheadline: "Unlimited solves, step-by-step, all subjects.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited solves"),
                    .init(systemImage: "bolt.fill", title: "Step-by-step"),
                    .init(systemImage: "nosign", title: "All subjects")
                ],
                productIDs: ["ai-tutor-solver_yearly", "ai-tutor-solver_weekly"],
                highlightedProductID: "ai-tutor-solver_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .blue, heroSystemImage: "text.bubble")
            )
        )
        return AppFactory(config)
    }
}

@main
struct AIHomeworkMathSolverApp: App {
    @StateObject private var factory = AIHomeworkMathSolverFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.blue)
        }
    }
}
